<?php
/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Starwars;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\ClientAbstract;
use Sdkgen\Client\Credentials;
use Sdkgen\Client\CredentialsInterface;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TokenStoreInterface;

class Client extends ClientAbstract
{
    public function people(): PeopleTag
    {
        return new PeopleTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function film(): FilmTag
    {
        return new FilmTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function starship(): StarshipTag
    {
        return new StarshipTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function species(): SpeciesTag
    {
        return new SpeciesTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function vehicle(): VehicleTag
    {
        return new VehicleTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function planet(): PlanetTag
    {
        return new PlanetTag(
            $this->httpClient,
            $this->parser
        );
    }



    public static function build(): self
    {
        return new self('https://swapi.dev/api', new Credentials\Anonymous());
    }
}
