<?php
/**
 * Collection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Starwars;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Collection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?int $count = null;
    #[Description('')]
    protected ?string $next = null;
    #[Description('')]
    protected ?string $previous = null;
    public function setCount(?int $count) : void
    {
        $this->count = $count;
    }
    public function getCount() : ?int
    {
        return $this->count;
    }
    public function setNext(?string $next) : void
    {
        $this->next = $next;
    }
    public function getNext() : ?string
    {
        return $this->next;
    }
    public function setPrevious(?string $previous) : void
    {
        $this->previous = $previous;
    }
    public function getPrevious() : ?string
    {
        return $this->previous;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('count', $this->count);
        $record->put('next', $this->next);
        $record->put('previous', $this->previous);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
