<?php
/**
 * Planet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Starwars;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('A Planet is a large mass, planet or planetoid in the Star Wars Universe, at the time of 0 ABY')]
class Planet implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $name = null;
    #[Description('')]
    protected ?string $diameter = null;
    #[Key('rotation_period')]
    #[Description('')]
    protected ?string $rotationPeriod = null;
    #[Key('orbital_period')]
    #[Description('')]
    protected ?string $orbitalPeriod = null;
    #[Description('')]
    protected ?string $gravity = null;
    #[Description('')]
    protected ?string $population = null;
    #[Description('')]
    protected ?string $climate = null;
    #[Description('')]
    protected ?string $terrain = null;
    #[Key('surface_water')]
    #[Description('')]
    protected ?string $surfaceWater = null;
    /**
     * @var array<string>|null
     */
    #[Description('')]
    protected ?array $residents = null;
    /**
     * @var array<string>|null
     */
    #[Description('')]
    protected ?array $films = null;
    #[Description('')]
    protected ?string $url = null;
    #[Description('')]
    protected ?\PSX\DateTime\LocalDateTime $created = null;
    #[Description('')]
    protected ?\PSX\DateTime\LocalDateTime $edited = null;
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setDiameter(?string $diameter): void
    {
        $this->diameter = $diameter;
    }
    public function getDiameter(): ?string
    {
        return $this->diameter;
    }
    public function setRotationPeriod(?string $rotationPeriod): void
    {
        $this->rotationPeriod = $rotationPeriod;
    }
    public function getRotationPeriod(): ?string
    {
        return $this->rotationPeriod;
    }
    public function setOrbitalPeriod(?string $orbitalPeriod): void
    {
        $this->orbitalPeriod = $orbitalPeriod;
    }
    public function getOrbitalPeriod(): ?string
    {
        return $this->orbitalPeriod;
    }
    public function setGravity(?string $gravity): void
    {
        $this->gravity = $gravity;
    }
    public function getGravity(): ?string
    {
        return $this->gravity;
    }
    public function setPopulation(?string $population): void
    {
        $this->population = $population;
    }
    public function getPopulation(): ?string
    {
        return $this->population;
    }
    public function setClimate(?string $climate): void
    {
        $this->climate = $climate;
    }
    public function getClimate(): ?string
    {
        return $this->climate;
    }
    public function setTerrain(?string $terrain): void
    {
        $this->terrain = $terrain;
    }
    public function getTerrain(): ?string
    {
        return $this->terrain;
    }
    public function setSurfaceWater(?string $surfaceWater): void
    {
        $this->surfaceWater = $surfaceWater;
    }
    public function getSurfaceWater(): ?string
    {
        return $this->surfaceWater;
    }
    /**
     * @param array<string>|null $residents
     */
    public function setResidents(?array $residents): void
    {
        $this->residents = $residents;
    }
    /**
     * @return array<string>|null
     */
    public function getResidents(): ?array
    {
        return $this->residents;
    }
    /**
     * @param array<string>|null $films
     */
    public function setFilms(?array $films): void
    {
        $this->films = $films;
    }
    /**
     * @return array<string>|null
     */
    public function getFilms(): ?array
    {
        return $this->films;
    }
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }
    public function getUrl(): ?string
    {
        return $this->url;
    }
    public function setCreated(?\PSX\DateTime\LocalDateTime $created): void
    {
        $this->created = $created;
    }
    public function getCreated(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->created;
    }
    public function setEdited(?\PSX\DateTime\LocalDateTime $edited): void
    {
        $this->edited = $edited;
    }
    public function getEdited(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->edited;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('name', $this->name);
        $record->put('diameter', $this->diameter);
        $record->put('rotation_period', $this->rotationPeriod);
        $record->put('orbital_period', $this->orbitalPeriod);
        $record->put('gravity', $this->gravity);
        $record->put('population', $this->population);
        $record->put('climate', $this->climate);
        $record->put('terrain', $this->terrain);
        $record->put('surface_water', $this->surfaceWater);
        $record->put('residents', $this->residents);
        $record->put('films', $this->films);
        $record->put('url', $this->url);
        $record->put('created', $this->created);
        $record->put('edited', $this->edited);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
